### ISSUE TITLE
No go vet results?

### ISSUE THREAD

**Issue by acook** [codeclimate-community/codeclimate-govet#11]
CodeClimate output (no go vet visible): https://codeclimate.com/github/acook/blacklight/issues
CodeClimate config: https://github.com/acook/blacklight/blob/master/.codeclimate.yml#L7-L8
Local output:

```
$ go vet src/*.go
src/meta.go:23: Value passes lock by value: main.Meta
src/meta.go:24: return copies lock value: main.Meta
src/meta.go:27: Print passes lock by value: main.Meta
src/meta.go:37: Refl passes lock by value: main.Meta
src/stack.go:38: Value passes lock by value: main.Stack
src/stack.go:39: return copies lock value: main.Stack
src/stack.go:42: Refl passes lock by value: main.Stack
src/stack.go:73: Print passes lock by value: main.Stack
exit status 1
```

**Comment by ABaldwinHunter** [comment]
@acook Thanks for the feedback! I believe this issue is related to our base go image being out of date. I've opened a pull to update it: https://github.com/codeclimate-community/codeclimate-govet/pull/12

Testing it out locally, this seems to fix the issue.

**Comment by ABaldwinHunter** [comment]
Hey @acook happy to report that that update is now live on our hosted site and in the CLI. 

I went ahead and forked your repo and it looks like govet issues are now present: https://codeclimate.com/github/ABaldwinHunter/blacklight/issues?category=&engine=govet

Could you go ahead and try pushing a new commit to see if that update fixes the issue you saw?

I'm going to go ahead and close this issue thread for now, but please feel free to reopen if any other issue comes up!

Thanks again for giving us a heads up about this problem :)
