### ISSUE TITLE
Missing results?

### ISSUE THREAD

**Issue by berfarah** [codeclimate-community/codeclimate-govet#20]
Hi! I think I might have a similar issue to what someone had mentioned about a year or so ago.

Here's a branch that has `go vet` issues: https://github.com/botopolis/slack/pull/1

```sh
go version # go version go1.9.3 darwin/amd64
go vet ./...
# stderr:
# action/action.go:29: Load passes lock by value: action.Plugin contains action.registry contains sync.Once contains sync.Mutex
# action/action.go:33: webhook passes lock by value: action.Plugin contains action.registry contains sync.Once contains sync.Mutex
# exit status 1
```

Here is that build on codeclimate: https://codeclimate.com/github/botopolis/slack/builds/11 (with 0 issues)

I've tried running CodeClimate locally:

```sh
brew tap codeclimate/formulae
brew install codeclimate
codeclimate engines:install
codeclimate analyze -e govet
# 0 issues
```

And re-building the plugin/engine (what determines whether something is one or the other, by the way?)

```sh
# Build the thing
git clone codeclimate-community/codeclimate-govet
cd codeclimate-govet
make
docker images # verified it's there and was just built
```

```sh
# In botopolis/slack
codeclimate analyze -e govet
# 0 issues
```

Please let me know if there's anything else I can help out with here. I'd also be happy to provide a PR if it's a simple fix.

**Comment by filipesperandio** [comment]
Closing this one up.
New changes were just merged, let us know if anything is still needed here and we can open it again.
Sorry the updates are taking long to get merged in.
